import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dotenv from "dotenv";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // fetch data from graphql
  let data;
  if (process.env.WORDPRESS_API_URL) {
    const response = await fetch(process.env.WORDPRESS_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        query: `
          query {
            posts {
              nodes {
                title
                excerpt
              }
            }
          }
        `,
      }),
    });
    data = await response.json();
  }

  console.log(JSON.stringify(data, null, 2));

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
